src-git packages https://github.com/openwrt/packages.git^32dd807af85e709fb0965aae58be9f50f8bef412
src-git luci https://github.com/openwrt/luci.git^dd3d1cbca298c11a409acb01ef644ee3c6892faf
src-git routing https://github.com/openwrt/routing.git^cc66db23430a923df3fe7941a097c5fd4040087b
